#!/bin/bash
# Build Transcriber.app: a menu bar launcher you can open from Spotlight or
# add to Login Items. It runs menubar.py with the project's virtualenv, which
# starts `python app.py` for you and opens http://localhost:5001.
#
#   ./make_app.sh                 -> ~/Applications/Transcriber.app
#   ./make_app.sh /Applications   -> /Applications/Transcriber.app (may need admin)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
DEST_DIR="${1:-$HOME/Applications}"
APP="$DEST_DIR/Transcriber.app"

if [ ! -x "$ROOT/.venv/bin/python" ]; then
  echo "No virtualenv at $ROOT/.venv. Run the Setup Playbook in README.md first." >&2
  exit 1
fi
"$ROOT/.venv/bin/python" -c "import rumps" 2>/dev/null || {
  echo "Installing the menu bar dependency (rumps)…"
  uv pip install --python "$ROOT/.venv/bin/python" rumps
}

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>Transcriber</string>
  <key>CFBundleDisplayName</key>     <string>Transcriber</string>
  <key>CFBundleIdentifier</key>      <string>local.transcriber.menubar</string>
  <key>CFBundleVersion</key>         <string>1.0</string>
  <key>CFBundleShortVersionString</key> <string>1.0</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>Transcriber</string>
  <key>LSMinimumSystemVersion</key>  <string>12.0</string>
  <key>LSUIElement</key>             <true/>
  <key>NSHighResolutionCapable</key> <true/>
  <key>NSMicrophoneUsageDescription</key>
  <string>Transcriber records meetings from your microphone and transcribes them on this Mac. Nothing leaves your computer.</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/Transcriber" <<LAUNCHER
#!/bin/bash
# Generated by make_app.sh — points at the project checkout below.
# Python is run as a CHILD (not exec'd): when the LaunchServices-registered
# process is replaced by python, macOS never lays out the menu bar item.
mkdir -p "\$HOME/Library/Logs/Transcriber"
cd "$ROOT"
"$ROOT/.venv/bin/python" "$ROOT/menubar.py" >> "\$HOME/Library/Logs/Transcriber/menubar.log" 2>&1 &
child=\$!
trap 'kill \$child 2>/dev/null' TERM INT HUP
wait \$child
LAUNCHER
chmod +x "$APP/Contents/MacOS/Transcriber"

# Ad-hoc signature so macOS remembers the microphone permission for this app.
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || true

echo "Built $APP"
echo "Open it with:  open \"$APP\"   (or search 'Transcriber' in Spotlight)"
echo "To start it at login: System Settings > General > Login Items > + > Transcriber"
